### ISSUE TITLE
Skeleton UI

### ISSUE THREAD

**Issue by Suremaker** [Suremaker/FileManager#1]
## Story
```
As a user
I want to run File Manager UI
So that I could use it to manage my files
```

## Tasks
* [x] Create Avalonia project
* [x] Create blank, resizeable main window
* [x] Handle application exit on window close

**Comment by Suremaker** [comment]
Implemented with https://github.com/Suremaker/FileManager/commit/bac33b45f8eca33911fff49cee22262200b84b15
