### ISSUE TITLE
Display directory content

### ISSUE THREAD

**Issue by Suremaker** [Suremaker/FileManager#2]
## Story
```
As a user
I want to see the current directory content
So that I can see all the files and directories in the current location
And decide what to do next
```

## Tasks
- [x] Create panel showing all files name and its type
- [x] Create label showing current directory location
- [x] Implement mechanism for retrieving directory content and file types

## Description
The UI will only contain this panel atm.
The panel will display the content of `the current directory`.
